/**
 * @license
 * Lo-Dash 1.0.1 (Custom Build) lodash.com/license
 * Build: `lodash --silent --output /private/var/folders/_b/2zt85gnd1r71_3h3lz3jnh9m0000gn/T/lodash11324-94131-mudsgx legacy include="isArray, isString, isFunction, each"`
 * Underscore.js 1.4.4 underscorejs.org/LICENSE
 */
;(function(n){function t(){}function r(n,t,r){if(null==n)return f;var e=typeof n;if("function"!=e){if("object"!=e)return function(t){return t[n]};var o=keys(n);return function(t){for(var r=o.length,e=!1;r--&&(e=isEqual(t[o[r]],n[o[r]],y)););return e}}return typeof t!="undefined"?1===r?function(r){return n.call(t,r)}:2===r?function(r,e){return n.call(t,r,e)}:4===r?function(r,e,o,i){return n.call(t,r,e,o,i)}:function(r,e,o){return n.call(t,r,e,o)}:n}function e(n){return n?v.call(n,"callee"):!1}function o(n){return typeof n=="function"
}function i(n){return typeof n=="string"||j.call(n)==b}function u(n,t,r){if(t&&typeof r=="undefined"&&k(n)){r=-1;for(var e=n.length;++r<e&&!1!==t(n[r],r,n););}else O(n,t,r);return n}function f(n){return n}var c=typeof exports=="object"&&exports,a=typeof module=="object"&&module&&module.exports==c&&module,l=typeof global=="object"&&global;l.global===l&&(n=l);var s,p,y=l={},d="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),v=l.hasOwnProperty,j=l.toString,b="[object String]",h=!0;
(function(){function n(){this.x=1}var t=[];n.prototype={valueOf:1,y:1};for(var r in new n)t.push(r);for(r in arguments)h=!r;s=!/valueOf/.test(t),p=n.propertyIsEnumerable("prototype")})(1);var m=arguments.constructor==Object,g="xx"!="x"[0]+Object("x")[0],x={"boolean":!1,"function":!0,object:!0,number:!1,string:!1,undefined:!1},O=function(){for(var n,t={e:s,f:p,i:h,j:g,k:d,b:"l(n)",c:"",h:"",l:"",m:!0},o=0;n=arguments[o];o++)for(var u in n)t[u]=n[u];if(n=t.a,t.d=/^[^,]+/.exec(n)[0],o=Function,u="var j,n="+t.d+",u=n;if(!n)return u;"+t.l+";",t.b?(u+="var o=n.length;j=-1;if("+t.b+"){",t.j&&(u+="if(m(n)){n=n.split('')}"),u+="while(++j<o){"+t.h+"}}else{"):t.i&&(u+="var o=n.length;j=-1;if(o&&k(n)){while(++j<o){j+='';"+t.h+"}}else{"),t.f&&(u+="var v=typeof n=='function';"),u+="for(j in n){",(t.f||t.m)&&(u+="if(",t.f&&(u+="!(v&&j=='prototype')"),t.f&&t.m&&(u+="&&"),t.m&&(u+="i.call(n,j)"),u+="){"),u+=t.h+";",(t.f||t.m)&&(u+="}"),u+="}",t.e){u+="var g=n.constructor;";
for(var f=0;7>f;f++)u+="j='"+t.k[f]+"';if(","constructor"==t.k[f]&&(u+="!(g&&g.prototype===n)&&"),u+="i.call(n,j)){"+t.h+"}"}return(t.b||t.i)&&(u+="}"),u+=t.c+";return u",o("f,i,k,l,m,r","return function("+n+"){"+u+"}")(r,v,e,k,i,x)}({a:"e,d,x",l:"d=d&&typeof x=='undefined'?d:f(d,x)",b:"typeof o=='number'",h:"if(d(n[j],j,e)===false)return u"}),k=function(n){return m&&n instanceof Array||"[object Array]"==j.call(n)};o(/x/)&&(o=function(n){return n instanceof Function||"[object Function]"==j.call(n)
}),t.forEach=u,t.each=u,t.identity=f,t.isArguments=e,t.isArray=k,t.isFunction=o,t.isString=i,t.VERSION="1.0.1",typeof define=="function"&&typeof define.amd=="object"&&define.amd?(n._=t,define(function(){return t})):c?a?(a.exports=t)._=t:c._=t:n._=t})(this);